name: Deploy Auto Sudoku Static Web App with Function App

on:
  push:
    branches:
      - main # Or your main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build React App
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or your node version

      - name: Install dependencies (React)
        run: |
          cd auto-sudoku
          npm install

      - name: Build React App
        run: |
          cd auto-sudoku
          npm run build
        env:
          VITE_APP_SOLVE_ENDPOINT: ${{ vars.SOLVE_ENDPOINT }}

      # Build Azure Function App (.NET 8) for Static Web App
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install .NET dependencies (Function App)
        run: |
          cd backend/AutoSudoku.Function
          dotnet restore

      - name: Build Function App for Static Web App
        run: |
          cd backend/AutoSudoku.Function
          dotnet publish -c Release -o ${{ github.workspace }}/backend/AutoSudoku.Function/api

      # Deploy React App and Function App to Azure Static Web App
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Needed for GitHub integration
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/auto-sudoku/build" # Location of your built app
          app_artifact_location: "." # location of the built app artifacts relative to app_location.