name: Deploy Auto Sudoku Static Web App with Function App

on:
  push:
    branches:
      - main # Or your main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build React App
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or your node version

      - name: Install dependencies (React)
        run: |
          cd auto-sudoku
          npm install

      - name: Build React App
        run: |
          cd auto-sudoku
          npm run build
        env:
          VITE_APP_SOLVE_ENDPOINT: ${{ vars.SOLVE_ENDPOINT }}

      # Build Azure Function App (.NET 8) for Static Web App
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install .NET dependencies (Function App)
        run: |
          cd backend/AutoSudoku.Function
          dotnet restore

      - name: Build Function App for Static Web App
        run: |
          cd backend/AutoSudoku.Function
          dotnet publish -c Release -o ${{ github.workspace }}/backend/AutoSudoku.Function/api

      # Deploy React App to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'auto-sudoku' # Replace with your Web App name
          slot-name: 'production' # Or your deployment slot
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './auto-sudoku/dist'